### ISSUE TITLE
Merge with upgrated official SDL Mixer

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/SDL-Mixer-X#6]
* Various Bugfixes
* MPG123 codec
* Rework of music.c, added super-different Music Interface than implemented in current version of SDL Mixer X
* Using of new SDL's Streamer thing with a clean resampling and a sound conversion

https://hg.libsdl.org/SDL_mixer/shortlog

# TODO List:
- [x] Extend Mix_MusicInterface structure with Mixer-X specific functions
- [x] Repair a support for meta-tags printing for OGG, GME, and added for ADLMIDI and OPNMIDI
- [x] Add splitting of post-path extra arguments
- [x] Improve the support for a dynamical MIDI device switching
- [x] Add Mix_PlayChannelTimedVolume and Mix_FadeInChannelTimedVolume, again
- [x] Fix an ability to set limited count of loops on looping OGG files
- [x] Implement missing functions in the header
- [x] Repair VB6 Binding on the Windows
- [x] Re-Implement full seekability for the Wave player
- [x] Re-Implement full seekability for MAD MP3 codec
- [x] Try to implement a full seekability for MPG123
- [x] Re-Implement support for ID3 Tags to retreive Meta-Tags from MP3 files
- [x] Repair seekability support for ModPlug
- [x] Repair meta-tags for ModPlug module
- [x] Re-Implement FLAC meta-tags and full seekability
- [x] Repair full support for path arguments and Open*Ex music interface functions
- [x] Fix broken SMPEG support
- [x] Fix broken Timidity custom paths support
- [x] Repair QMake build
- [x] Fix missing reset of ADLMIDI settings after using of path arguments
- [x] Fix handling of RMI MIDI files

**Comment by Wohlstand** [comment]
The complete merge is completed and all known issues has been fixed!
For now the testing is needed and later polishing of the working code.
