### ISSUE TITLE
Send all changes of fork to official SDL Mixer

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/SDL-Mixer-X#8]
All changes made on this fork are will be useful on original SDL Mixer too. Changes are must be applied accurate and result must be build-able through same set of toolchains as supported on original SDL Mixer

## Todo
- [x] Main part (Features, improvements)
- [x] ~~Customized libID3Tag library into "external" folder with revived autotools support (which was dropped away)~~ Replaced with own code to parse ID3 and other tags in MP3 files
- ~~Autotools build support for GME, ADLMIDI, and OPNMIDI~~ No needed at all, SDL3 drops away the autotools support.
- [ ] New audio codecs (GME, ADLMIDI, OPNMIDI) into "external" folder
- [ ] Mix_InitMixer(), Mix_FreeMixer(), and callback retrievers
- [ ] Multi-Music system and new `*Stream*` calls

## Stuff
* The repository to merge stuff: https://github.com/Wohlstand/SDL_mixer
* Issue on official SDL_mixer bug tracker: https://github.com/libsdl-org/SDL_mixer/issues/233

## Toolchains
* Automake
* Visual Studio projects of various versions
* XCode project(s)

**Comment by Wohlstand** [comment]
First part of changes [has been sent as pull-request](https://bitbucket.org/Wohlstand/sdl_mixer/commits/524433869ae11d0fb56a1464dfb75b498911e39f) except of GME, ADLMIDI and OPNMIDI support, and libID3Tag library itself as that requires to add them into "external" subfolder and provide support for autotools build.

**Comment by vilhelmgray** [comment]
I suspect you're more likely to get a response if you submit a message to the SDL Development mailing list: https://discourse.libsdl.org/t/about-the-sdl-development-category/13

It looks like the bugzilla is primarily for bug tracking, but since you are trying to merge in many new features, your pull request may have better luck in the SDL Development mailing list.

I'd really like to see these improvements in SDL Mixer X merged back into the SDL Mixer project since your changes look very useful, and I'm hoping the SDL developers will also agree. :-)

**Comment by Wohlstand** [comment]
Yeah, first off I going to backport guts without libraries and APIs yet:
- [x] GUTS: most bug and warning fixes made in MixerX
- [ ] FORMATS: extending of WAV parser (I have polished it to support much more WAV formats which wasn't supported good). Looks like I'll port this now, it can be backported now
- [ ] GUTS: extending of `Mix_MusicInterface` with new calls
- [ ] API: Ability to set custom patches path for Timidity (for example, allow game developer to pick-up own bank with a game and don't rely on these are installed in the system).
- [ ] API & GUTS: ability to switch MIDI device in real time (will add new API calls), adding support of path arguments to allow select the MIDI library by using of `|sX;` tail.
- [ ] API: meta-tags
- [ ] API: more music related calls
- [ ] API: more SFX related calls (mainly `Mix_PlayChanTimedVolume()` to solve one of oldest problems when we usually getting old volume value of channel and we can't tell which volume we want to play, mainly, when we using `-1` for automatical look up of the channel index)
- [ ] API + GUTS: this https://github.com/WohlSoft/SDL-Mixer-X/pull/20
- [ ] FORMATS & API: Adding a support for more format libraries (ADLMIDI, OPNMIDI, GME and XMP), adding specific API to allow tuning of every of these libraries

**Comment by Wohlstand** [comment]
@vilhelmgray, after time of waiting, Sam have finally replied on my post I have submitted on SDL's bugzilla. So, right now I working on a submitting of patches to Mixer

**Comment by Wohlstand** [comment]
Since the whole mainstream thing was majorly changed, this is no longer needed. This variant of MixerX would go by just its own path, but keeping an eye to mainstream Mixer for tweaks and fixes. Actually, since this was happen, I can apply my own improvements without looking on the mainstream Mixer, but ensure the API compatibility with the original Mixer. Additionally, the SDL3 version of MixerX is still needed to be made.
